- hosts: devops

  tasks:

    - name: Install go
      apt: name=golang-go state=present
  
    - name: Install php fpm
      apt: name=php-fpm state=present
    
    - name: Create dir for goapp and maingo bin
      file: path=/srv/goapp/src/ state=directory

    - name: Copy main.go
      template: src=templates/main.go.j2 dest=/srv/goapp/main.go
      

    - name:  build goapp
      shell: go build /srv/goapp/main.go
      args: 
        chdir: /srv/goapp/src/

    - name: Create systemd goapp.service
      template: src=templates/systemd.maingo.service.conf.j2 dest=/etc/systemd/system/goapp.service

    - name: Start goapp.service
      shell: systemctl start goapp.service
      args:
        chdir: ~

    - name: Create dir for phpapp
      file: path=/srv/phpapp/ state=directory

    - name: Copy diff.php
      template: src=templates/phpapp.diff.php.j2 dest=/srv/phpapp/diff.php


