
- hosts: all
  gather_facts: no
  tasks:
    - name: Install python
      raw: apt-get update && apt install python2.7 -y && update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
    
    - name: Create a 2048-bit SSH key for user jsmith in ~jsmith/.ssh/id_rsa
      user: name=root generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa

