- hosts: devops

  tasks:

    - name: Install go
      apt: name=golang-go state=present
  
    - name: Install php fpm
      apt: name=php-fpm state=present
    
    - name: Create dir for goapp and maingo bin
      file: path=/srv/goapp/src/ state=directory

    - name: Copy main.go
      copy: src=~/ansible/files/main.go dest=/srv/goapp/main.go
    
    - name:  Build goapp
      shell: go build /srv/goapp/main.go
      args:
        chdir: /srv/goapp/src/

    - name: Create systemd goapp.service
      template: src=templates/systemd.maingo.service.conf.j2 dest=/etc/systemd/system/goapp.service

    - name: Start goapp.service
      shell: systemctl start goapp.service
      args:
        chdir: ~

    - name: Create dir for phpapp
      file: path=/srv/phpapp/ state=directory

    - name: Copy diff.php
      copy: src=~/ansible/files/diff.php dest=/srv/phpapp/diff.php

